services:
  api:
    image: ghcr.io/jtryno/s26-cpsc4910-team11-api:latest
    environment:
      PORT: "5000"
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_NAME: "${DB_NAME}"
    expose:
      - "5000"
    restart: unless-stopped

  web:
    image: ghcr.io/jtryno/s26-cpsc4910-team11-web:latest
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped