name: Publish Docker images to GHCR

on:
  push:
    branches: [ "feature/image-action" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: driver-incentive-program
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image vars
        run: |
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"
          echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
          echo "REPO_LC=${REPO,,}" >> $GITHUB_ENV

      - name: Build and push API
        run: |
          IMAGE="ghcr.io/$OWNER_LC/$REPO_LC-api:latest"
          docker buildx build --platform linux/amd64 -f server/Dockerfile -t "$IMAGE" --push .

      - name: Build and push WEB
        run: |
          IMAGE="ghcr.io/$OWNER_LC/$REPO_LC-web:latest"
          docker buildx build --platform linux/amd64 -f Dockerfile -t "$IMAGE" --push .